### ISSUE TITLE
PostBound's implimentation

### ISSUE THREAD

**Issue by Nesar7650** [rbergm/PostBOUND#4] opened 2023-07-24 09:31 UTC
want to implimentaation PostBound and i faced some problems during the implementation of PostBound. Unfortunately, the dataset job couldn't be copied and executed properly. It seems that I have issues with Postgresconfig. Would you mind please letting me know about the detail ?
and the other error that i faced is when i want to run ues-generator.py:

#############

pg_ctl: another server might be running; trying to start server anyway
waiting for server to start...... done
server started
(postbound) shima@shima-IdeaPad-3-15ITL6:~/postbound$ cd ues
(postbound) shima@shima-IdeaPad-3-15ITL6:~/postbound/ues$ python3 ues-generator.py
/home/shima/postbound/ues/transform/db.py:157: UserWarning: No .psycopg_connection file found, trying empty connect string as last resort. This is likely not intentional.
  warnings.warn("No .psycopg_connection file found, trying empty connect string as last resort. This "
Traceback (most recent call last):
  File "ues-generator.py", line 17, in <module>
    from transform import db, mosp, ues, util
  File "/home/shima/postbound/ues/transform/ues.py", line 65, in <module>
    class MospQueryPreparation:
  File "/home/shima/postbound/ues/transform/ues.py", line 81, in MospQueryPreparation
    def __init__(self, query: mosp.MospQuery, *, dbs: db.DBSchema = db.DBSchema.get_instance()):
  File "/home/shima/postbound/ues/transform/db.py", line 163, in get_instance
    conn = psycopg2.connect(psycopg_connect, application_name="PostBOUND")
  File "/home/shima/anaconda3/envs/postbound/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

########
please give more information about how config postgresql step by step.
It could be worth mentioning that I try to implementation this framework on ubuntu.

**Comment by rbergm** [comment] 2023-07-24 12:43
The error you are describing is a pretty well-known one. Sadly, it is caused by insufficient documentation on my end. Here’s what’s going on: when you start the ues generator, it tries to establish a connection to the Postgres instance on which you want to optimize and execute your workload. However, in order to do so, the generator needs to know what database instance this is and how it can find it. The way this is done is by using a so-called connect file. Basically, this is a hidden file called .psycopg_connection that you have to place in the root directory from which you are calling the generator. Inside of the file you have to put a connection string. This is your configuration on a single line. It will be passed to the pyscopg library (v2) that is used by PostBOUND under the hood, so it has to be compatible with this tool. You can try to establish a connection via psycopg first to figure out which string works. Once you found one, save it to the connect file. Afterwards, the generator should run as expected.

On a different note: PostBOUND is currently undergoing some major restructuring and improvements that will enhance pretty much every detail of the framework. This work is happening on the quality/grand-refactor branch and is nearing its completion. I am currently in the process of finalizing the documentation and expect it to be ready within the next two weeks. Depending on your time schedule and your use case, you might want to start using this version, rather than the legacy release that you are currently using. I have been doing so in a couple of productive scenarios for the last couple of weeks so there should not be any major bugs and the documentation is much better (plus, there are a couple of experiments that can serve as usage examples).

I hope I was able to clarify some of the confusion around the framework.

**Comment by rbergm** [comment] 2023-08-03 22:11
I just merged the first stage of the reworked PostBOUND implementation into the `main` branch. You should now be able to use this new version. Sadly, this merge does not yet include an extensive user documentation. However, pretty much all the important parts of the framework have a large API documentation that was designed to act as replacement for such a user documentation to some extent. Please refer to the [README](https://github.com/rbergm/PostBOUND/blob/main/postbound/README.md) of the PostBOUND package to familiarize yourself with the new framework.

**Comment by rbergm** [comment] 2023-08-29 21:03
Closing this issue now since the discussion seems to be inactive. If you have further questions, feel free to open a new issue!

**Closed as completed by rbergm** 2023-08-29 21:03 UTC
Labels: question
