### ISSUE TITLE
Inquiry about Stable Version and Recent Changes

### ISSUE THREAD

**Issue by themaqs** [rbergm/PostBOUND#5] opened 2023-08-23 23:47 UTC
Hello,

I hope you are doing well. I have a couple of inquiries regarding the repository:

1. I was wondering which commit represents the stable version of the article. Could you please point me to the specific commit corresponding to the stable release?

2. Currently, continuous changes are being made in the repository. While running the experiments using the codebase, I encountered logical Python errors. These errors seem to be stemming from recent changes made to the codebase.

I appreciate your assistance in clarifying these points. Thank you for your time and effort in maintaining this repository.

Best regards,
Aydin

**Comment by rbergm** [comment] 2023-08-24 08:29
Hey Aydin,

thank you for your interest in the PostBOUND project. I hope you will find the framework useful in your research!

Which specific article are you referring to? Are you talking about _PostBOUND: PostgreSQL with Upper Bound SPJ Query Optimization_ (BTW'23, Bergmann et al.)? If that is the case, there is a dedicated branch called `btw23-reproducibility`. However, this branch contains a much older snapshot of the repository and lacks a high-level documentation. Nevertheless, the README in the `btw-scripts` can get you started.

If you are not focused on reproducing the old experiments from BTW'23, you should use the latest PostBOUND version of the `main` branch. This provides a much more polished and extended implementation of the framework which also contains extensive documentation. Once again, the READMEs should serve as a starting point.

Regarding your second question: I am sorry you encoutered errors when using PostBOUND. Can you provide some details about the specific error and your setup, as well as the version of PostBOUND (head commit) you were using? Generally speaking the `main` branch is intended to provide the latest stable version of the framework. If commits are made directly to this branch, they should be backwards-compatible. All development of new functionality happens on dedicated feature branches that are eventually merged back into `main`. These branches are not necessarily stable in terms of bugs as well as interfaces and breaking changes.

I hope this clarifies some of your questions. Feel free to follow up if necessary.

Best,
Rico

**Comment by rbergm** [comment] 2023-08-29 21:04
Closing this issue now since the discussion seems to be inactive. If you have further questions, feel free to open a new issue!

**Closed as completed by rbergm** 2023-08-29 21:04 UTC
Labels: question
